export const ENV = {
  ALLOW_PASS: process.env.REACT_APP_REACT_APP_ALLOW_PASS,
  COGNITO_USERPOOL : process.env.REACT_APP_REACT_APP_COGNITO_USERPOOL,
  COGNITO_CLIENT : process.env.REACT_APP_REACT_APP_COGNITO_CLIENT,
  COGNITO_IDENTITY_POOL : process.env.REACT_APP_REACT_APP_COGNITO_IDENTITY_POOL,
  REGION : process.env.REACT_APP_REACT_APP_REGION,
  HOST : process.env.REACT_APP_API_URL,
  STRIPE_PUBLIC : process.env.REACT_APP_REACT_STRIPE_PUBLIC,
  GRAPHQL_URL: process.env.REACT_APP_API_URL
};
